//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SCIM.Schemas {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SchemasResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SchemasResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SCIM.Schemas.SchemasResources", typeof(SchemasResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The event token has expired. ähnelt.
        /// </summary>
        internal static string ExceptionEventTokenExpired {
            get {
                return ResourceManager.GetString("ExceptionEventTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This value is invalid for the claim, {0}: {1}. ähnelt.
        /// </summary>
        internal static string ExceptionEventTokenInvalidClaimValueTemplate {
            get {
                return ResourceManager.GetString("ExceptionEventTokenInvalidClaimValueTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The token is missing a value for this required claim: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionEventTokenMissingClaimTemplate {
            get {
                return ResourceManager.GetString("ExceptionEventTokenMissingClaimTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An attribute is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidAttribute {
            get {
                return ResourceManager.GetString("ExceptionInvalidAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This identifier is invalid: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidIdentifierTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidIdentifierTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This type of resource can only have one resource type schema identifier: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionMultipleQualifiedResourceTypeIdentifiersTemplate {
            get {
                return ResourceManager.GetString("ExceptionMultipleQualifiedResourceTypeIdentifiersTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A value greater than zero is required for this argument: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionPostiveIntegerRangeTemplate {
            get {
                return ResourceManager.GetString("ExceptionPostiveIntegerRangeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following cannot be assigned to the &quot;value&quot; attribute of an Azure Active Directory role: {0}.  It exceeds the maximum permissible length for that attribute, which is this many characters: {1}. ähnelt.
        /// </summary>
        internal static string ExceptionRoleValueLengthExceededTemplate {
            get {
                return ResourceManager.GetString("ExceptionRoleValueLengthExceededTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only a single event was expected. ähnelt.
        /// </summary>
        internal static string ExceptionSingleEventExpected {
            get {
                return ResourceManager.GetString("ExceptionSingleEventExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An authentication scheme must have a name. ähnelt.
        /// </summary>
        internal static string ExceptionUnnamedAuthenticationScheme {
            get {
                return ResourceManager.GetString("ExceptionUnnamedAuthenticationScheme", resourceCulture);
            }
        }
    }
}
