//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SCIM.Protocol {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProtocolResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProtocolResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SCIM.Protocol.ProtocolResources", typeof(ProtocolResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This filter is invalid: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidFilterTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This operator is not supported: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidOperatorTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperatorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This path is invalid: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidPathTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidPathTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The request is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidRequest {
            get {
                return ResourceManager.GetString("ExceptionInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A resource is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This count value is invalid: {0}.  A non-negative number is expected. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidSearchRequestCountTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidSearchRequestCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This sort order value is invalid: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidSortOrderTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidSortOrderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This start index value is invalid: {0}.  The start index is a 1-based index. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidStartIndexTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidStartIndexTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A value is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A bulk operation must have a unique identifier. ähnelt.
        /// </summary>
        internal static string ExceptionUnidentifiableOperation {
            get {
                return ResourceManager.GetString("ExceptionUnidentifiableOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The schema could not be identified. ähnelt.
        /// </summary>
        internal static string ExceptionUnidentifiableSchema {
            get {
                return ResourceManager.GetString("ExceptionUnidentifiableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}/{1}. ähnelt.
        /// </summary>
        internal static string ResourceIdentifierTemplate {
            get {
                return ResourceManager.GetString("ResourceIdentifierTemplate", resourceCulture);
            }
        }
    }
}
