//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.SCIM.Service {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServiceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.SCIM.Service.ServiceResources", typeof(ServiceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filtering by this attribute is not supported: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionFilterAttributePathNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterAttributePathNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only a query with exactly one filter is supported. ähnelt.
        /// </summary>
        internal static string ExceptionFilterCount {
            get {
                return ResourceManager.GetString("ExceptionFilterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The filter is not supported. ähnelt.
        /// </summary>
        internal static string ExceptionFilterNotSupported {
            get {
                return ResourceManager.GetString("ExceptionFilterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This filter operator is not supported: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionFilterOperatorNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterOperatorNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A batch is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidBatch {
            get {
                return ResourceManager.GetString("ExceptionInvalidBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The context is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidContext {
            get {
                return ResourceManager.GetString("ExceptionInvalidContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An identifier is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidIdentifier {
            get {
                return ResourceManager.GetString("ExceptionInvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An operation is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidOperation {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The operation with this identifier is not valid: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidOperationTemplate {
            get {
                return ResourceManager.GetString("ExceptionInvalidOperationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The parameters are invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The request is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidRequest {
            get {
                return ResourceManager.GetString("ExceptionInvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The resource is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The response is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidResponse {
            get {
                return ResourceManager.GetString("ExceptionInvalidResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The state is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidState {
            get {
                return ResourceManager.GetString("ExceptionInvalidState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The requested state transition is invalid. ähnelt.
        /// </summary>
        internal static string ExceptionInvalidStateTransition {
            get {
                return ResourceManager.GetString("ExceptionInvalidStateTransition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This method is not supported: {0}. ähnelt.
        /// </summary>
        internal static string ExceptionMethodNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionMethodNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The monitoring behavior has not been properly initialized. ähnelt.
        /// </summary>
        internal static string ExceptionNotInitializedMonitoringBehavior {
            get {
                return ResourceManager.GetString("ExceptionNotInitializedMonitoringBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The provider behavior has not been properly initialized. ähnelt.
        /// </summary>
        internal static string ExceptionNotInitializedProviderBehavior {
            get {
                return ResourceManager.GetString("ExceptionNotInitializedProviderBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pagination is not supported for this type of resource: {0} ähnelt.
        /// </summary>
        internal static string ExceptionPaginationIsNotSupportedTemplate {
            get {
                return ResourceManager.GetString("ExceptionPaginationIsNotSupportedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The query is not supported. ähnelt.
        /// </summary>
        internal static string ExceptionQueryNotSupported {
            get {
                return ResourceManager.GetString("ExceptionQueryNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: {1} ähnelt.
        /// </summary>
        internal static string HeaderTemplate {
            get {
                return ResourceManager.GetString("HeaderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data has been read. ähnelt.
        /// </summary>
        internal static string InformationRead {
            get {
                return ResourceManager.GetString("InformationRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Processing of this request was completed: {0}.  
        ///
        ///The status code of the response was {1} ähnelt.
        /// </summary>
        internal static string InformationRequestProcessedTemplate {
            get {
                return ResourceManager.GetString("InformationRequestProcessedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This request was received: {0}. ähnelt.
        /// </summary>
        internal static string InformationRequestReceivedTemplate {
            get {
                return ResourceManager.GetString("InformationRequestReceivedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data has been written. ähnelt.
        /// </summary>
        internal static string InformationWrote {
            get {
                return ResourceManager.GetString("InformationWrote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1}
        ///{2} ähnelt.
        /// </summary>
        internal static string MessageTemplate {
            get {
                return ResourceManager.GetString("MessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}@ ähnelt.
        /// </summary>
        internal static string MonitorCorrelationIdentifierPrefixTemplate {
            get {
                return ResourceManager.GetString("MonitorCorrelationIdentifierPrefixTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: {1} (Critical? {2}) ähnelt.
        /// </summary>
        internal static string MonitorOutputExceptionTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputExceptionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: {1} (Verbose? {2}) ähnelt.
        /// </summary>
        internal static string MonitorOutputInformationTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputInformationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}: {1} ähnelt.
        /// </summary>
        internal static string MonitorOutputTemplate {
            get {
                return ResourceManager.GetString("MonitorOutputTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die , ähnelt.
        /// </summary>
        internal static string SeparatorHeaderValues {
            get {
                return ResourceManager.GetString("SeparatorHeaderValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The supplied watermark did not match the expected watermark: 
        ///Supplied: 
        ///{0}
        ///Received: 
        ///{1} ähnelt.
        /// </summary>
        internal static string WarningUnexpectedWatermarkTemplate {
            get {
                return ResourceManager.GetString("WarningUnexpectedWatermarkTemplate", resourceCulture);
            }
        }
    }
}
